version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : taskapi
    expose:
      - 3306
    volumes:
      - ./MYSQL:/var/lib/mysql

  restapi:
    build:
      dockerfile: API/Dockerfile
      context: .
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8000:8000
